import {
  Essentials, Paragraph, Bold, Italic, Underline, Strikethrough, Undo, Heading, List, TodoList,
  Link, Table, TableToolbar, BlockQuote, Font, Subscript, Superscript, Code, CodeBlock,
  HorizontalLine, Indent, IndentBlock, Alignment, Image, ImageToolbar, ImageCaption,
  ImageStyle, RemoveFormat, SourceEditing,
} from 'ckeditor5';


export const ckeditorConfig = {
  licenseKey: 'GPL',

  plugins: [
    Essentials,
    Paragraph,
    Bold,
    Italic,
    Underline,
    Strikethrough,
    Undo,
    Heading,
    List,
    TodoList,
    Link,
    Table,
    TableToolbar,
    BlockQuote,
    Font,
    Subscript,
    Superscript,
    Code,
    CodeBlock,
    HorizontalLine,
    Indent,
    IndentBlock,
    Alignment,
    Image,
    ImageToolbar,
    ImageCaption,
    ImageStyle,
    RemoveFormat,
    SourceEditing,
  ],

  toolbar: {
    items: [
      'undo',
      'redo',
      '|',
      'heading',
      '|',
      'fontSize',
      'fontFamily',
      'fontColor',
      'fontBackgroundColor',
      '|',
      'bold',
      'italic',
      'underline',
      'strikethrough',
      'subscript',
      'superscript',
      'code',
      '|',
      'link',
      'insertTable',
      'blockQuote',
      'codeBlock',
      'horizontalLine',
      '|',
      'bulletedList',
      'numberedList',
      'todoList',
      '|',
      'outdent',
      'indent',
      '|',
      'alignment',
      '|',
      'removeFormat',
      '|',
      'sourceEditing',
    ],

    shouldNotGroupWhenFull: false,
  },
  fontSize: {
    options: [8, 10, 12, 14, 16, 18, 20, 22, 24],
    supportAllValues: false,
  },
  table: {
    contentToolbar: [
      'tableColumn',
      'tableRow',
      'mergeTableCells',
      'tableCellProperties',
      'tableProperties',
    ],
  },
  image: {
    toolbar: [
      'imageTextAlternative',
      'toggleImageCaption',
      'imageStyle:inline',
      'imageStyle:block',
      'imageStyle:side',
    ],
  },

  placeholder: 'Введите описание...',
};
